---
- hosts: jumpbox
  tasks:
  - name: Remove all instance
    include_role:
       name: osp-remove-instances
       vars_from: "{{ item }}"
    loop:
      - frontend.yaml
      - app1.yaml
      - app2.yaml
      - db.yaml

  - name: Remove a flavor
    include_role:
      name: osp-remove-flavor

  - name: Remove Security Groups
    include_role:
      name: osp-remove-securitygroup

  - name: Remove key pair
    include_role:
      name: osp-remove-keypair

  - name: Remove all networks
    include_role:
      name: osp-remove-networ
